"""
Action: Scroll LinkedIn feed and collect posts.
FILE: automation/actions/feed_scroll.py

Navigates to the LinkedIn feed, scrolls naturally, and extracts post content
for scoring. Uses existing human-like behavior functions.

Includes robust modern selectors + explicit waits + heavy debug logging + screenshots.

ROOT CAUSE THIS FILE FIXES (Aug 2026)
-------------------------------------
LinkedIn migrated the main feed page (https://www.linkedin.com/feed/) from
semantic BEM class names (e.g. ``div.feed-shared-update-v2``,
``.scaffold-finite-scroll__item``, ``.update-components-text``,
``.feed-shared-actor__name``) to CSS modules with hashed class names
(e.g. ``_0e43c9fa``, ``_8895db18``).  Every class-based selector below matched
ZERO elements on the new feed page, so the page scrolled fine (native page
scrolling still works) but post extraction found no post containers and every
scan stored 0 posts.

The new feed page keeps stable attributes, so extraction now relies on:
  * ``[data-testid="mainFeed"] [role="listitem"]`` for post containers,
  * ``data-urn`` / ``data-id`` / ``data-activity-urn`` (when present),
  * the post permalink ``a[href*="/feed/update/..."]`` for the activity URN
    and a stable post URL,
  * whole-item text (cleaned of Like/Comment/Repost/Send chrome) as a text
    fallback since LinkedIn removed stable selectors for the post body.

The old BEM selectors are kept as fallbacks because LinkedIn still serves them
on some surfaces (e.g. profile / recent-activity pages).
"""
import asyncio
import hashlib
import random
import re
import time
from urllib.parse import urlsplit, urlunsplit
from patchright.async_api import Page
from automation.human import human_scroll, random_idle_pause
from automation.actions.utils import recover_blank_page
from core.logging_config import get_logger, should_log_debug, should_take_screenshots

logger = get_logger(__name__)

# Force screenshots during feed scroll scans even outside dev mode.
# This is extremely valuable for debugging "why no posts?" issues.
FORCE_FEED_SCREENSHOTS = True

# ── Post container selectors, ordered by preference ──────────────────────────
# The new feed page (CSS modules) has NO semantic classes; its stable anchor is
# [data-testid="mainFeed"] [role="listitem"].  Everything else is kept as a
# fallback for older DOM variants and non-feed surfaces.
POST_CONTAINER_SELECTORS = [
    # NEW feed page (CSS modules) — stable attributes only
    "[data-testid='mainFeed'] [role='listitem']",
    "[data-testid='mainFeed'] [role='article']",
    # urn/id/activity-carrying containers (work on old & new DOM)
    "div[data-urn]",
    "article[data-urn], article[data-id]",
    "div[data-urn*='activity'], div[data-id*='activity'], div[data-activity-urn]",
    "div[data-urn^='urn:li:activity']",
    # Legacy BEM feed containers (still served on some surfaces)
    "div.feed-shared-update-v2",
    "div.occludable-update",
    "li.scaffold-finite-scroll__content > li",
    "div.scaffold-finite-scroll__item",
    "li.feed-shared-update-v2",
    "div.update-components-update",
    "div[class*='feed-shared-update'], div[class*='occludable-update'], div[class*='update-components']",
    # Broad semantic fallbacks (strict filtering applies to these)
    "div[role='article']",
    "div[role='listitem']",
]

# Selector used to detect "did LinkedIn append new posts after scrolling?"
DOM_COUNT_SELECTOR = ", ".join(POST_CONTAINER_SELECTORS)

# Broad fallbacks that can match non-post cards (right rail, carousels, nav).
# For these we demand a real post fingerprint (activity urn / permalink) and do
# not accept mere "has text" as evidence.
_STRICT_CONTAINER_SELECTORS = {
    "div[role='listitem']",
    "div[role='article']",
}

# Anchor for the post permalink (used for URN + URL extraction).
POST_LINK_SELECTOR = (
    # A feed permalink can be rendered as either /feed/update/... or the
    # newer /posts/<author>/...-activity-... form.  Do not rely solely on the
    # feed URL: LinkedIn frequently supplies the latter in the CSS-modules UI.
    "a[href*='/feed/update/'], a[href*='/posts/'], a[href*='urn:li:activity'], "
    "a[href*='urn:li:ugcPost'], a[href*='urn:li:share'], a[href*='activity-']"
)

# LinkedIn truncates long post copy behind several equivalent controls.  These
# are deliberately text controls only; "More actions" and "More comments" are
# excluded so an extraction never opens a menu or comments thread.
_EXPAND_POST_TEXT_SELECTOR = "button, [role='button'], a, span"

# URN kinds that identify a POST/activity.  Feed item wrappers and actor
# containers both expose data-urn; only these kinds identify the post itself
# (author/entity URNs such as urn:li:person:... must never be used as post
# URNs, otherwise all posts from one author collapse into a single "post").
# The permalink-href fallback below catches any future post URN kinds too.
_POST_URN_TYPES = {"activity", "ugcPost", "share", "fsd_update", "update", "comment"}

# Lines generated by LinkedIn's UI chrome around a post (reaction buttons,
# counters, collapsers) that must not end up in the scored post text.
_UI_NOISE_LINE = re.compile(
    r"^(like|comment|repost|send|share|react|reactions?|celebrate|support|love|"
    r"insightful|funny|more|see more|see less|\.\.\.|…)$"
    r"|^[0-9.,kmb+]+[ ]*(likes?|comments?|reposts?|reactions?|followers?|"
    r"connections?|views?)?$",
    re.IGNORECASE,
)


def _should_screenshot() -> bool:
    """Always take screenshots for feed scroll diagnostics."""
    return FORCE_FEED_SCREENSHOTS or should_take_screenshots()


# ── Pure helpers (unit-testable without a browser) ───────────────────────────

def _is_post_urn(value: str | None) -> bool:
    """True when a URN string identifies a post/activity, not an author entity."""
    if not value or not isinstance(value, str):
        return False
    if not value.startswith("urn:li:"):
        return False
    parts = value.split(":")
    if len(parts) < 3 or not parts[2]:
        return False
    return parts[2] in _POST_URN_TYPES


def _urn_from_href(href: str | None) -> str | None:
    """Extract a real activity URN from a post permalink href.

    Handles the shapes LinkedIn actually serves:
      /feed/update/urn:li:activity:7123456789012345678/
      /feed/update/urn:li:ugcPost:7123456789012345678
      /feed/update/urn:li:share:7123456789012345678
      /feed/update/7123456789012345678
      .../activity-7123456789012345678-...
    """
    if not href:
        return None
    m = re.search(r"/feed/update/(urn:li:[a-zA-Z_]+:\d+)", href)
    if m and _is_post_urn(m.group(1)):
        return m.group(1)
    m = re.search(r"urn:li:(?:activity|ugcPost|share|fsd_update|update|comment):\d+", href)
    if m:
        return m.group(0)
    m = re.search(r"/feed/update/(\d+)", href)
    if m:
        return f"urn:li:activity:{m.group(1)}"
    m = re.search(r"activity-(\d+)", href)
    if m:
        return f"urn:li:activity:{m.group(1)}"
    return None


def _normalise_post_url(href: str | None, post_urn: str | None = None) -> str | None:
    """Return an absolute, clickable LinkedIn post URL.

    LinkedIn often renders post permalinks as relative hrefs (``/posts/...`` or
    ``/feed/update/...``).  Storing those directly makes the frontend navigate
    inside our own app instead of opening LinkedIn, so normalize at extraction
    time and also allow a URN fallback for older rows.
    """
    cleaned = (href or "").strip()
    if cleaned:
        cleaned = cleaned.split("?", 1)[0].split("#", 1)[0]
        if cleaned.startswith("//www.linkedin.com/"):
            cleaned = f"https:{cleaned}"
        elif cleaned.startswith("/"):
            cleaned = f"https://www.linkedin.com{cleaned}"
        elif cleaned.startswith("www.linkedin.com/"):
            cleaned = f"https://{cleaned}"

        if cleaned.startswith(("https://www.linkedin.com/", "http://www.linkedin.com/")) and (
            "/feed/update/" in cleaned or "/posts/" in cleaned or "activity-" in cleaned
        ):
            return cleaned.replace("http://www.linkedin.com/", "https://www.linkedin.com/", 1)

        # Sometimes the href itself is only a URN-ish value.  Convert it below.
        urn = _urn_from_href(cleaned)
        if urn:
            return f"https://www.linkedin.com/feed/update/{urn}/"

    if post_urn and post_urn.startswith("urn:li:"):
        return f"https://www.linkedin.com/feed/update/{post_urn}/"
    return None


def _post_identity_key(
    post_urn: str | None,
    post_url: str | None = None,
    author_name: str | None = None,
    post_text: str | None = None,
) -> str:
    """Stable key for deduping posts collected through different DOM paths.

    The same feed card can be discovered as both a wrapper and a nested update,
    and LinkedIn may expose ``urn:li:activity`` in one place but only a
    ``/posts/...activity-...`` permalink in another.  Dedupe by the underlying
    activity id first, then normalized URL, then a content hash fallback.
    """
    url = _normalise_post_url(post_url, post_urn)
    urn = _urn_from_href(url or "") or (post_urn if _is_post_urn(post_urn) else None)
    if urn:
        m = re.search(r":(\d+)$", urn)
        if m:
            return f"activity:{m.group(1)}"
        return f"urn:{urn}"

    if url:
        try:
            parts = urlsplit(url)
            path = re.sub(r"/+$", "", parts.path)
            return "url:" + urlunsplit((parts.scheme.lower(), parts.netloc.lower(), path, "", ""))
        except Exception:
            return f"url:{url.lower()}"

    text = " ".join((post_text or "").lower().split())[:1200]
    author = " ".join((author_name or "").lower().split())
    digest = hashlib.md5(f"{author}|{text}".encode("utf-8", "ignore")).hexdigest()[:16]
    return f"text:{digest}"


def _is_expand_post_text_control(text: str | None, aria_label: str | None = None) -> bool:
    """Return whether a control expands the current post's truncated copy.

    LinkedIn changes the visible copy between ``...more``, ``See more`` and
    ``Show more``.  Matching labels precisely prevents accidental clicks on
    the unrelated More-actions menu and comment expansion controls.
    """
    label = " ".join(f"{text or ''} {aria_label or ''}".lower().split())
    # Normalise the ellipsis prefix used by the compact feed renderer.
    label = label.replace("…", "...").lstrip(". ")
    if not label:
        return False
    if any(blocked in label for blocked in ("comment", "reply", "action", "menu", "reaction")):
        return False

    # Exact labels and common aria labels.
    if label in {"more", "see more", "show more"}:
        return True
    if (label.startswith("see more") or label.startswith("show more")) and any(
        hint in label for hint in ("post", "text", "content")
    ):
        return True

    # Some current LinkedIn variants use aria text like "click to see more".
    # Keep this bounded so a long post body ending with "...more" is not treated
    # as the control itself when we scan spans inside the post.
    return len(label) <= 80 and ("see more" in label or "show more" in label)


def _pseudo_urn(author_name: str | None, post_text: str | None) -> str:
    """Stable fallback URN for posts with no real URN in the DOM.

    Uses md5 instead of the builtin ``hash()``, which is randomized per
    process (PYTHONHASHSEED), so the same post dedups consistently within a
    scan AND across scans.
    """
    key = f"{author_name or ''} | {post_text or ''}"
    digest = hashlib.md5(key.encode("utf-8", "ignore")).hexdigest()[:16]
    return f"post_{digest}"


def _clean_post_text(raw: str | None) -> str:
    """Strip LinkedIn's UI chrome from a post's text and collapse whitespace.

    Removes lines that are only reaction buttons / counters / collapsers
    (e.g. "Like", "Comment", "Repost", "Send", "1,234", "2.3K reactions") so
    the scored text is the actual post content.
    """
    lines = []
    for line in (raw or "").splitlines():
        line = line.strip()
        if not line:
            continue
        if _UI_NOISE_LINE.match(line):
            continue
        lines.append(line)
    cleaned = " ".join(lines)
    # If LinkedIn did not expand the copy (or expansion failed), the compact
    # renderer can leave an inline trailing "...more" / "…more" token.  It is a
    # control label, not post content; stripping it also avoids scoring the word
    # "more" and showing a fake, non-clickable "more" in our UI.
    cleaned = re.sub(r"\s*(?:\.{3}|…)\s*more\s*$", "", cleaned, flags=re.IGNORECASE)
    return cleaned[:2500]


# ── Main flow ────────────────────────────────────────────────────────────────

async def scroll_feed_and_collect(
    page: Page,
    target_posts: int = 20,
    max_scrolls: int = 15,
) -> list[dict]:
    """
    Navigate to LinkedIn feed, scroll naturally, and extract posts.

    Args:
        page: Playwright page object
        target_posts: Number of posts to try to collect
        max_scrolls: Maximum number of scroll iterations

    Returns:
        List of dicts with keys: post_urn, post_url, author_name, post_text
    """
    collected_posts = []
    seen_urns = set()

    try:
        # Navigate to the feed
        logger.info("Navigating to LinkedIn feed...")
        feed_url = "https://www.linkedin.com/feed/"
        await page.goto(feed_url, wait_until="domcontentloaded", timeout=30000)
        await random_idle_pause(2, 4)

        # Blank-page recovery (wait for render → reload → session probe → retry)
        recovered, load_error, session_stale = await recover_blank_page(page, feed_url)
        if not recovered:
            logger.error("❌ Feed failed to load: %s (session_stale=%s)", load_error, session_stale)
            return []

        # Verify we're on the feed
        if "/feed" not in page.url:
            logger.warning(f"Unexpected URL after navigating to feed: {page.url}")
            return []

        logger.info("✅ Feed page loaded. Waiting for posts to render...")

        # === NEW: Explicit wait + debug screenshot (FORCED for diagnostics) ===
        if _should_screenshot():
            try:
                await page.screenshot(path="feed_initial_load.png", full_page=True)
                logger.info("📸 Saved feed_initial_load.png")
            except Exception:
                pass

        # Wait for at least one post container to appear (critical!)
        try:
            await page.wait_for_selector(
                "[data-testid='mainFeed'] [role='listitem'], "
                "div[data-urn], article, [data-urn*='activity'], "
                "div.feed-shared-update-v2, div.update-components-text, "
                "div[role='listitem'], a[href*='/feed/update/'], "
                ".scaffold-finite-scroll__item, .occludable-update",
                timeout=12000,
                state="attached"
            )
            logger.info("✅ At least one post-like element detected on feed")
        except Exception as wait_err:
            logger.warning(f"⚠️ No post container appeared within timeout: {wait_err}")
            if _should_screenshot():
                try:
                    await page.screenshot(path="feed_no_posts_after_wait.png", full_page=True)
                    logger.info("📸 Saved feed_no_posts_after_wait.png")
                except Exception:
                    pass

        # Small extra settle time for lazy-loaded content
        await random_idle_pause(1.5, 3.0)

        # === Extra diagnostic: count key selectors ===
        try:
            for diag_sel in [
                "[data-testid='mainFeed'] [role='listitem']",
                "div[data-urn]",
                "article",
                "div.feed-shared-update-v2",
                "a[href*='/feed/update/']",
            ]:
                try:
                    count = await page.locator(diag_sel).count()
                    if count > 0:
                        logger.info(f"📍 Diagnostic: {count} elements matched '{diag_sel}'")
                except Exception:
                    pass
        except Exception:
            pass

        logger.info("Starting feed scroll to collect posts...")

        # Track how many post-like elements exist in the DOM so we can tell
        # whether LinkedIn actually appended new content after each scroll.
        dom_post_count = await _count_dom_posts(page)

        for scroll_iteration in range(max_scrolls):
            if len(collected_posts) >= target_posts:
                logger.info(f"Collected {len(collected_posts)} posts, stopping scroll")
                break

            # Extract posts from current view
            new_posts = await _extract_visible_posts(page, seen_urns)
            added_this_pass = 0
            for post in new_posts:
                identity = _post_identity_key(
                    post.get("post_urn"), post.get("post_url"),
                    post.get("author_name"), post.get("post_text")
                )
                if identity not in seen_urns and post.get("post_urn") not in seen_urns:
                    seen_urns.add(identity)
                    if post.get("post_urn"):
                        seen_urns.add(post["post_urn"])
                    collected_posts.append(post)
                    added_this_pass += 1
                    logger.info(f"✅ Collected post #{len(collected_posts)}: {post.get('author_name', 'Unknown')[:40]}... (len={len(post.get('post_text',''))})")

            if added_this_pass == 0:
                logger.info(f"Scroll pass {scroll_iteration + 1}: 0 new posts extracted (total so far: {len(collected_posts)})")

            # === NEW: debug screenshot per scroll pass (FORCED) ===
            if _should_screenshot() and scroll_iteration % 3 == 0:
                try:
                    await page.screenshot(path=f"feed_scroll_pass_{scroll_iteration+1}.png", full_page=True)
                    logger.info(f"📸 Saved feed_scroll_pass_{scroll_iteration+1}.png")
                except Exception:
                    pass

            # Scroll naturally AND make sure LinkedIn actually loads more posts.
            # Bare mouse.wheel() often doesn't move LinkedIn's own scroll
            # container in headless mode, so the feed never grows and we end up
            # re-reading the same one screenful of posts.  We therefore also
            # scroll the real container with JS and wait for the DOM count to
            # increase before counting the pass as useful.
            old_dom_count = dom_post_count
            dom_post_count = await _feed_scroll_and_wait_for_new_posts(page, old_dom_count)

            if dom_post_count > old_dom_count:
                logger.info(
                    f"Scroll {scroll_iteration + 1}: LinkedIn loaded more posts "
                    f"(DOM {old_dom_count} -> {dom_post_count})"
                )
            else:
                logger.warning(
                    f"Scroll {scroll_iteration + 1}: no new posts loaded by LinkedIn "
                    f"(DOM still {dom_post_count}) - infinite scroll may not be triggering"
                )

            await random_idle_pause(1.5, 3.0)

            logger.info(f"Scroll {scroll_iteration + 1}/{max_scrolls}: collected {len(collected_posts)} posts so far")

        if len(collected_posts) == 0:
            logger.error("❌ CRITICAL: Feed scroll finished with ZERO posts collected after all scrolls!")
            if _should_screenshot():
                try:
                    await page.screenshot(path="feed_final_zero_posts.png", full_page=True)
                    logger.info("📸 Saved feed_final_zero_posts.png (last state)")
                except Exception:
                    pass

        logger.info(f"Feed scroll complete. Collected {len(collected_posts)} posts total")
        return collected_posts

    except Exception as e:
        logger.error(f"Error during feed scroll: {e}")
        return collected_posts


async def _count_dom_posts(page: Page) -> int:
    """Count post-like elements currently in the DOM (regardless of viewport)."""
    try:
        return await page.locator(DOM_COUNT_SELECTOR).count()
    except Exception:
        return 0


async def _feed_scroll_and_wait_for_new_posts(
    page: Page,
    current_dom_count: int,
    max_wait: float = 10.0,
) -> int:
    """
    Scroll down far enough to trigger LinkedIn's infinite-scroll lazy loader,
    then wait until new posts are actually appended to the DOM.

    Root cause this fixes: a bare ``page.mouse.wheel()`` frequently does NOT
    move LinkedIn's feed in headless Chromium because the feed lives inside its
    own scrollable container (e.g. ``.scaffold-layout__main`` /
    ``.scaffold-finite-scroll__content``), so the window scrolls but the feed
    never grows and the same one screenful of posts is collected over and over.
    (The current CSS-modules feed uses native page scrolling, which the JS
    below also covers via ``document.scrollingElement`` / ``window.scrollTo``.)

    We drive the scroll both with the human-style wheel and with explicit JS
    that scrolls every scrollable candidate container to its bottom, then poll
    the DOM until the post count increases (new content loaded) or we time out.

    Returns the new post-element count in the DOM.
    """
    # Human-style wheel nudge first (keeps behaviour realistic).
    try:
        await page.mouse.move(720, 480)
    except Exception:
        pass
    await human_scroll(page)

    # Guarantee the real feed scroll container actually moves.
    try:
        await page.evaluate(
            """() => {
                const scroll = (el) => {
                    if (!el) return;
                    if (el.scrollHeight > el.clientHeight + 5) {
                        el.scrollTop = el.scrollHeight;
                    }
                };
                // Window / document scrolling element
                const doc = document.scrollingElement || document.documentElement;
                scroll(doc);
                window.scrollTo(0, document.body.scrollHeight);
                // Candidate feed scroll containers
                for (const sel of [
                    '[data-testid="mainFeed"]',
                    '.scaffold-layout__main',
                    '.scaffold-finite-scroll__content',
                    '.scaffold-finite-scroll__item',
                    'main',
                    '[class*="finite-scroll"]',
                    '[class*="feed"]'
                ]) {
                    document.querySelectorAll(sel).forEach(scroll);
                }
            }"""
        )
    except Exception as e:
        logger.debug(f"JS feed scroll failed: {e}")

    # Wait for the post count in the DOM to grow (LinkedIn appends new posts).
    deadline = time.monotonic() + max_wait
    while time.monotonic() < deadline:
        count = await _count_dom_posts(page)
        if count > current_dom_count:
            return count
        await asyncio.sleep(0.8)

    return current_dom_count


async def _looks_like_post(element, strict: bool = False) -> bool:
    """Cheap sanity check that an element is really a feed post, not chrome.

    With ``strict=True`` (used for the broad ``[role='listitem']`` fallback)
    a real post fingerprint is required — an activity URN or a post permalink
    link.  Otherwise long text is accepted as evidence too.
    """
    try:
        for attr in ("data-urn", "data-id", "data-activity-urn"):
            val = await element.get_attribute(attr)
            if _is_post_urn(val):
                return True
        link = await element.query_selector(POST_LINK_SELECTOR)
        if link:
            return True
        if strict:
            return False
        txt = await element.inner_text()
        return bool(txt and len(txt.strip()) > 30)
    except Exception:
        return not strict  # be permissive when we cannot inspect


async def _expand_post_text(element) -> bool:
    """Expand a truncated post in-place before reading its text.

    The control must be searched *within the post container*.  A page-level
    ``get_by_text('More')`` is unsafe because it commonly targets the profile
    card's More-actions menu instead of the post body.  LinkedIn currently
    renders the expander sometimes as a button and sometimes as a clickable
    span inside the post body, so we inspect both and click the nearest
    clickable ancestor when needed.
    """
    try:
        controls = await element.query_selector_all(_EXPAND_POST_TEXT_SELECTOR)
        for control in controls[:300]:
            try:
                text = await control.inner_text()
                aria_label = await control.get_attribute("aria-label")
                try:
                    parent_context = await control.evaluate(
                        """el => {
                            const target = el.closest('button,[role="button"],a') || el;
                            return [
                                target.getAttribute('aria-label') || '',
                                target.getAttribute('data-control-name') || ''
                            ].join(' ');
                        }"""
                    )
                except Exception:
                    parent_context = ""
                if not _is_expand_post_text_control(text, f"{aria_label or ''} {parent_context}"):
                    continue
                # Patchright may return detached controls while React replaces
                # a feed item.  Scroll first and let the next scan retry it.
                if hasattr(control, "scroll_into_view_if_needed"):
                    await control.scroll_into_view_if_needed(timeout=2500)
                try:
                    await control.click(timeout=3000)
                except Exception:
                    # Spans containing "...more" may not be directly clickable;
                    # trigger the closest clickable ancestor in the browser.
                    await control.evaluate(
                        """el => {
                            const target = el.closest('button,[role="button"],a') || el;
                            target.click();
                        }"""
                    )
                await asyncio.sleep(0.5)  # wait for the full copy to render
                return True
            except Exception:
                continue
    except Exception:
        pass
    return False


async def _extract_visible_posts(page: Page, seen_urns: set) -> list[dict]:
    """
    Extract post data from currently visible feed items.

    Returns list of dicts with: post_urn, post_url, author_name, post_text
    """
    posts = []
    local_seen_keys = set()

    post_elements = []
    for selector in POST_CONTAINER_SELECTORS:
        try:
            elements = await page.query_selector_all(selector)
            if elements:
                strict = selector in _STRICT_CONTAINER_SELECTORS
                # Filter to only elements that look like real feed posts
                filtered = []
                for el in elements:
                    try:
                        if await _looks_like_post(el, strict=strict):
                            filtered.append(el)
                    except Exception:
                        filtered.append(el)  # be permissive
                    if len(filtered) >= 80:  # sanity cap per pass
                        break

                if filtered:
                    post_elements = filtered
                    logger.info(f"🔍 Found {len(filtered)} potential posts using selector: {selector}")
                    break
        except Exception as e:
            logger.debug(f"Selector {selector} failed: {e}")
            continue

    if not post_elements:
        logger.warning("⚠️ _extract_visible_posts: No post elements found with any selector")
        if _should_screenshot():
            try:
                await page.screenshot(path="feed_extract_no_elements.png", full_page=True)
                logger.info("📸 Saved feed_extract_no_elements.png")
            except Exception:
                pass
        return posts

    logger.info(f"🔍 Attempting to extract data from {len(post_elements)} post elements")

    for idx, element in enumerate(post_elements):
        try:
            # Long posts only expose a preview until their local See more /
            # ...more button is clicked.  Expand before text and URL extraction
            # so scoring sees the complete post, not the truncated preview.
            expanded = await _expand_post_text(element)
            if expanded and should_log_debug():
                logger.debug("Expanded truncated text for feed post %s", idx)

            # Extract post text first (it is also used for the URN fallback).
            post_text = await _get_post_text(element)
            if not post_text or len(post_text.strip()) < 15:  # relaxed from 20
                if should_log_debug():
                    logger.debug(f"Post {idx}: text too short or empty ({len(post_text or '')} chars), skipping")
                continue

            # Extract author name
            author_name = await _get_author_name(element)

            # Extract URN (unique identifier) — real URN or stable fallback
            post_urn = await _get_post_urn(element, author_name, post_text)
            if not post_urn:
                continue

            # Build post URL (prefer the real permalink href)
            post_url = await _get_post_url(element, post_urn)
            identity = _post_identity_key(post_urn, post_url, author_name, post_text)
            if post_urn in seen_urns or identity in seen_urns or identity in local_seen_keys:
                continue
            local_seen_keys.add(identity)

            posts.append({
                "post_urn": post_urn,
                "post_url": post_url,
                "author_name": author_name,
                "post_text": post_text,
            })

            if should_log_debug():
                logger.debug(f"Extracted post {len(posts)}: urn={post_urn[:30]}... text_len={len(post_text)}")

        except Exception as e:
            logger.debug(f"Error extracting post data (idx={idx}): {e}")
            continue

    return posts


async def _get_post_urn(element, author_name: str | None = None, post_text: str | None = None) -> str | None:
    """Extract the URN from a post element. More aggressive now.

    Order of attempts:
      1. Activity-ish ``data-urn`` / ``data-id`` / ``data-activity-urn`` on the
         element itself.
      2. The post permalink href (``/feed/update/urn:li:activity:...``),
         preferred before descendant URNs because nested social/comment nodes can
         expose their own activity URNs.
      3. Same attributes on any descendant (skipping author/entity URNs such as
         ``urn:li:person:...`` which would otherwise be mistaken for the post).
      4. A stable pseudo-URN derived from author + text.
    """
    try:
        # 1. Own attributes
        for attr in ("data-urn", "data-id", "data-activity-urn", "data-activityid"):
            try:
                val = await element.get_attribute(attr)
                if _is_post_urn(val):
                    return val
            except Exception:
                continue

        # 2. Permalink href (works on the new CSS-modules feed).  Prefer this
        # before descendant data-urns: nested social/comment elements can expose
        # their own URNs, while the permalink points to the actual feed card.
        try:
            link = await element.query_selector(POST_LINK_SELECTOR)
            if link:
                href = await link.get_attribute("href")
                urn = _urn_from_href(href or "")
                if urn:
                    return urn
        except Exception:
            pass

        # 3. Descendant attributes — iterate ALL, skip author/entity URNs
        for attr in ("data-urn", "data-id", "data-activity-urn"):
            try:
                descendants = await element.query_selector_all(f"[{attr}]")
                for child in descendants:
                    val = await child.get_attribute(attr)
                    if _is_post_urn(val):
                        return val
            except Exception:
                continue

        # 4. Stable pseudo-URN (still useful for dedup in same run)
        return _pseudo_urn(author_name, post_text)

    except Exception as e:
        if should_log_debug():
            logger.debug(f"_get_post_urn failed: {e}")
        return None


async def _get_post_url(element, post_urn: str | None) -> str | None:
    """Build an absolute post URL, preferring the real permalink href."""
    try:
        link = await element.query_selector(POST_LINK_SELECTOR)
        if link:
            href = await link.get_attribute("href")
            normalised = _normalise_post_url(href, post_urn)
            if normalised:
                # Preserve the real post permalink rather than fabricating a
                # feed URL. /posts/... links are the only link supplied for many
                # current feed cards, but they must be absolute for our UI.
                return normalised
    except Exception:
        pass

    return _normalise_post_url(None, post_urn)


async def _get_post_text(element) -> str:
    """Extract the main text content from a post element. Much more aggressive."""
    try:
        # Updated 2025/2026 text selectors (order matters).  NOTE: LinkedIn's
        # CSS-modules feed no longer has stable classes for the body, so these
        # mostly help on the legacy DOM; the fallback below cleans whole-item
        # text on the new feed.
        text_selectors = [
            "div.update-components-text",
            "div.feed-shared-update-v2__description",
            "div.feed-shared-text",
            "div[class*='update-components-text']",
            "div[class*='feed-shared-text']",
            ".feed-shared-inline-show-more-text",
            "div[class*='feed-shared-inline-show-more-text']",
        ]

        for selector in text_selectors:
            try:
                text_el = await element.query_selector(selector)
                if text_el:
                    text = await text_el.inner_text()
                    if text and len(text.strip()) > 12:
                        cleaned = " ".join(text.strip().split())
                        return cleaned[:2500]
            except Exception:
                continue

        # Fallback 1: whole-element text, cleaned of UI chrome.  On the new
        # CSS-modules feed this is the only way to get the post body.
        try:
            all_text = await element.inner_text()
            cleaned = _clean_post_text(all_text)
            if len(cleaned) > 15:
                return cleaned
        except Exception:
            pass

        # Fallback 2: largest text block (helps on image/video-only posts)
        try:
            paragraphs = await element.query_selector_all("p, span[dir='ltr']")
            best = ""
            for p in paragraphs:
                try:
                    t = await p.inner_text()
                    if len(t) > len(best):
                        best = t
                except Exception:
                    continue
            cleaned = _clean_post_text(best)
            if len(cleaned) > 15:
                return cleaned
        except Exception:
            pass

        # Fallback 3: raw element text
        full_text = await element.inner_text()
        return _clean_post_text(full_text)

    except Exception as e:
        if should_log_debug():
            logger.debug(f"_get_post_text failed: {e}")
        return ""


async def _get_author_name(element) -> str | None:
    """Extract the author's name from a post element. More robust."""
    try:
        author_selectors = [
            # Modern
            "a[href*='/in/'] span[aria-hidden='true']",
            "span.feed-shared-actor__name",
            "a.actor-description span",
            "div.feed-shared-actor__meta a",
            "h3 span[aria-hidden='true']",
            # Legacy
            "a.feed-shared-actor__description",
            "span.feed-shared-actor__name",
            "a.actor-description",
            "[data-control-name='actor_container'] span",
        ]

        for selector in author_selectors:
            try:
                author_el = await element.query_selector(selector)
                if author_el:
                    name = await author_el.inner_text()
                    name = (name or "").strip()
                    if name and len(name) > 1 and not name.lower().startswith(("like", "comment", "repost")):
                        return name[:80]
            except Exception:
                continue

        # Last-ditch: look for any prominent link near top
        try:
            links = await element.query_selector_all("a[href*='/in/']")
            for link in links[:2]:
                txt = await link.inner_text()
                if txt and len(txt.strip()) > 2 and len(txt.strip()) < 60:
                    return txt.strip()[:80]
        except Exception:
            pass

        return None

    except Exception as e:
        if should_log_debug():
            logger.debug(f"_get_author_name failed: {e}")
        return None
