"""Tests for the per-section admin API (accounts / LinkedIn jobs / WhatsApp jobs).

These back the admin module's own sidebar (Accounts → Users → LinkedIn →
WhatsApp). Each endpoint must tolerate empty tables and return sensible
shapes once rows exist.
"""
import os
import unittest

os.environ.setdefault("DATABASE_URL", "sqlite+aiosqlite:///:memory:")
os.environ.setdefault("PASSWORD_RESET_URL", "http://localhost/reset")
os.environ.setdefault("BACKEND_CORS_ORIGINS", "http://localhost")
os.environ.setdefault("RESEND_API_KEY", "test")
os.environ.setdefault("FROM_EMAIL", "test@example.com")
os.environ.setdefault("REDIS_URL", "redis://localhost:6379/0")
os.environ.setdefault("CREDENTIAL_ENCRYPTION_KEY", "a" * 64)
os.environ.setdefault("JWT_SECRET", "test")

from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine  # noqa: E402

from database import Base  # noqa: E402
from models.campaign import Campaign, CampaignStatus  # noqa: E402
from models.campaign_job import CampaignJob, JobStatus  # noqa: E402
from models.linkedin_account import LinkedInAccount  # noqa: E402
from models.user import User  # noqa: E402
from models.whatsapp import (  # noqa: E402
    WhatsAppRawMessage,
    WhatsAppScanFilter,
    WhatsAppSession,
)


async def _make_session():
    engine = create_async_engine("sqlite+aiosqlite:///:memory:")
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    return engine, async_sessionmaker(engine, expire_on_commit=False)


async def _seed(db):
    db.add(
        User(
            first_name="Admin",
            last_name="User",
            email="admin@test.dev",
            hashed_password="x",
            is_verified=True,
            role="admin",
        )
    )
    account = LinkedInAccount(
        owner_email="admin@test.dev",
        linkedin_email="li@test.dev",
        encrypted_password="enc",
        label="Work",
        profile_dir="/tmp/profiles/li",
        status="active",
    )
    db.add(account)
    db.add(WhatsAppSession(status="connected", is_active=True))

    campaign = Campaign(
        id="camp-1",
        account_email="li@test.dev",
        name="Q3 Founders",
        status=CampaignStatus.ACTIVE,
    )
    db.add(campaign)
    db.add(
        CampaignJob(
            id="job-1",
            campaign_id="camp-1",
            lead_id="lead-1",
            step_type="send_connection",
            status=JobStatus.DONE,
            action_message="Connection sent",
        )
    )

    db.add(WhatsAppScanFilter(name="Dubai Engineering Jobs", status="active", role="Engineer"))
    await db.commit()

    # The filter id is generated by SQLite's autoincrement; re-read it.
    result = await db.execute(WhatsAppScanFilter.__table__.select())
    filter_row = result.first()
    filter_id = filter_row.id if filter_row else None

    db.add(
        WhatsAppRawMessage(
            filter_id=filter_id,
            group_id=1,
            sender_name="Recruiter",
            message_text="Python dev needed",
            status="matched",
            forwarded=True,
        )
    )
    db.add(
        WhatsAppRawMessage(
            filter_id=filter_id,
            group_id=1,
            sender_name="Recruiter",
            message_text="Another post",
            status="rejected",
        )
    )
    await db.commit()


class AdminSectionApiTests(unittest.IsolatedAsyncioTestCase):
    async def asyncSetUp(self):
        self.engine, self.Session = await _make_session()
        async with self.Session() as db:
            await _seed(db)

    async def asyncTearDown(self):
        await self.engine.dispose()

    async def test_accounts_lists_linkedin_and_whatsapp_rows(self):
        from api.v1.admin import admin_accounts

        async with self.Session() as db:
            response = await admin_accounts(None, db)

        self.assertEqual(response.counts["linkedin_total"], 1)
        self.assertEqual(response.counts["linkedin_active"], 1)
        self.assertEqual(response.counts["whatsapp_total"], 1)
        self.assertEqual(response.counts["whatsapp_connected"], 1)
        self.assertEqual(response.linkedin[0].linkedin_email, "li@test.dev")
        self.assertEqual(response.whatsapp[0].status, "connected")

    async def test_linkedin_jobs_join_campaign_names(self):
        from api.v1.admin import admin_linkedin_jobs

        async with self.Session() as db:
            response = await admin_linkedin_jobs(limit=200, _admin=None, db=db)

        self.assertEqual(response.count, 1)
        self.assertEqual(response.jobs[0].campaign_name, "Q3 Founders")
        self.assertEqual(response.jobs[0].step_type, "send_connection")
        self.assertEqual(response.jobs[0].status, "done")

    async def test_whatsapp_jobs_include_message_counters(self):
        from api.v1.admin import admin_whatsapp_jobs

        async with self.Session() as db:
            response = await admin_whatsapp_jobs(limit=200, _admin=None, db=db)

        self.assertEqual(response.count, 1)
        job = response.jobs[0]
        self.assertEqual(job.name, "Dubai Engineering Jobs")
        self.assertEqual(job.total_count, 2)
        self.assertEqual(job.matched_count, 1)
        self.assertEqual(job.forwarded_count, 1)
        self.assertEqual(job.rejected_count, 1)


if __name__ == "__main__":
    unittest.main()
