"""YouTube service OAuth tests: deterministic PKCE end to end.

Regression tests for:

    invalid_grant: Missing code verifier

``google-auth-oauthlib`` auto-generates a code verifier when a Flow is built.
The old code built a Flow in ``get_auth_url`` (verifier generated and lost),
then a *fresh* Flow in ``exchange_code`` (a different auto-generated verifier),
so the token request carried no verifier for the ``code_challenge`` Google had
stored at authorization time. These tests pin the new behaviour: one verifier
is generated by the caller, handed to BOTH Flow instances (with automatic
generation disabled), and the S256 challenge on the authorization URL is
derived from that same verifier.
"""
import asyncio
import base64
import hashlib
import os
import time
import unittest
from unittest.mock import patch
from urllib.parse import parse_qs, urlparse

from jose import jwt

os.environ.setdefault("DATABASE_URL", "sqlite+aiosqlite:///:memory:")
os.environ.setdefault("REDIS_URL", "redis://localhost:6379/0")
os.environ.setdefault("CREDENTIAL_ENCRYPTION_KEY", "a" * 64)
os.environ.setdefault("JWT_SECRET", "test-secret")

from api.v1.social_scheduler import _mint_oauth_state, _read_oauth_state  # noqa: E402
from core.config import settings  # noqa: E402
from services.social.pkce import (  # noqa: E402
    generate_code_verifier,
    is_valid_code_verifier,
)
from services.social.youtube import YouTubeService  # noqa: E402

REDIRECT = "http://localhost:8000/api/v1/social-scheduler/platforms/youtube/callback"


def _challenge(verifier: str) -> str:
    """S256 challenge Google expects for a given code verifier."""
    digest = hashlib.sha256(verifier.encode("utf-8")).digest()
    return base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")


class CodeVerifierHelpersTests(unittest.TestCase):
    def test_generate_code_verifier_is_rfc7636_shaped(self):
        verifier = generate_code_verifier()
        self.assertEqual(len(verifier), 128)
        self.assertTrue(is_valid_code_verifier(verifier))

    def test_validator_rejects_bad_shapes(self):
        for bad in (None, "", "short", "x" * 129, "x" * 42, "!" * 43):
            self.assertFalse(is_valid_code_verifier(bad), bad)
        self.assertFalse(is_valid_code_verifier("x" * 43 + "="))
        self.assertTrue(is_valid_code_verifier(generate_code_verifier(43)))
        self.assertTrue(is_valid_code_verifier(generate_code_verifier(128)))


class YouTubeOAuthPkceTests(unittest.TestCase):
    def setUp(self):
        self._settings = patch.multiple(
            settings,
            YOUTUBE_CLIENT_ID="yt-id",
            YOUTUBE_CLIENT_SECRET="yt-secret",
            YOUTUBE_REDIRECT_URI=REDIRECT,
        )
        self._settings.start()
        self.service = YouTubeService()

    def tearDown(self):
        self._settings.stop()

    def test_auth_url_uses_the_caller_verifier_and_matching_s256_challenge(self):
        # The Flow must be built with the explicit verifier and automatic
        # generation OFF — otherwise the callbacks's fresh Flow would generate
        # a different verifier and Google rejects the code.
        from google_auth_oauthlib.flow import Flow

        original_from_client_config = Flow.from_client_config
        captured = {}

        def spy(client_config, scopes, **kwargs):
            captured["kwargs"] = kwargs
            return original_from_client_config(client_config, scopes=scopes, **kwargs)

        verifier = generate_code_verifier()
        with patch.object(Flow, "from_client_config", side_effect=spy):
            url = self.service.get_auth_url("state-token", code_verifier=verifier)

        self.assertEqual(captured["kwargs"].get("code_verifier"), verifier)
        self.assertFalse(
            captured["kwargs"].get("autogenerate_code_verifier"),
            "automatic PKCE generation must be off so both flows share one verifier",
        )
        self.assertEqual(captured["kwargs"].get("redirect_uri"), REDIRECT)

        qs = parse_qs(urlparse(url).query)
        self.assertEqual(qs["state"], ["state-token"])
        self.assertEqual(qs["redirect_uri"], [REDIRECT])
        self.assertEqual(qs["code_challenge_method"], ["S256"])
        self.assertEqual(qs["code_challenge"], [_challenge(verifier)])

    def test_exchange_code_sends_the_same_verifier_to_the_token_endpoint(self):
        from requests_oauthlib import OAuth2Session

        captured = {}

        def fake_fetch_token(session, token_url, **kwargs):
            captured["url"] = token_url
            captured["kwargs"] = kwargs
            session.token = {
                "access_token": "at-1",
                "refresh_token": "rt-1",
                "expires_in": 3600,
                "expires_at": time.time() + 3600,
            }
            return session.token

        verifier = generate_code_verifier()
        with patch.object(OAuth2Session, "fetch_token", fake_fetch_token):
            tokens = asyncio.run(self.service.exchange_code("auth-code", code_verifier=verifier))

        self.assertEqual(captured["url"], "https://oauth2.googleapis.com/token")
        self.assertEqual(captured["kwargs"]["code"], "auth-code")
        # This is the regression assertion: the callback must forward the
        # verifier from the signed state instead of sending none.
        self.assertEqual(captured["kwargs"]["code_verifier"], verifier)
        self.assertEqual(tokens["access_token"], "at-1")
        self.assertEqual(tokens["refresh_token"], "rt-1")
        self.assertGreaterEqual(tokens["expires_in"], 3599)

    def test_exchange_code_without_verifier_fails_before_any_network_call(self):
        from requests_oauthlib import OAuth2Session

        with patch.object(
            OAuth2Session,
            "fetch_token",
            side_effect=AssertionError("token endpoint must not be called without a verifier"),
        ):
            with self.assertRaisesRegex(ValueError, "code verifier"):
                asyncio.run(self.service.exchange_code("auth-code"))

    def test_signed_state_round_trips_the_verifier_and_stays_authoritative(self):
        verifier = generate_code_verifier()
        state = _mint_oauth_state("owner@test.dev", "youtube", code_verifier=verifier)
        payload = _read_oauth_state(state, "youtube")
        self.assertEqual(payload["sub"], "owner@test.dev")
        self.assertEqual(payload["platform"], "youtube")
        self.assertEqual(payload["code_verifier"], verifier)

        # Provider/state validation must remain intact (no weakening):
        # wrong platform, forged signature, and malformed verifier are all
        # rejected before any token exchange happens.
        with self.assertRaises(ValueError):
            _read_oauth_state(state, "tiktok")
        forged = jwt.encode(
            {"sub": "attacker@test.dev", "platform": "youtube",
             "token_type": "social_oauth_state", "code_verifier": verifier},
            "wrong-secret", algorithm="HS256",
        )
        with self.assertRaises(ValueError):
            _read_oauth_state(forged, "youtube")
        malformed = _mint_oauth_state("owner@test.dev", "youtube", code_verifier="x" * 5)
        with self.assertRaises(ValueError):
            _read_oauth_state(malformed, "youtube")


if __name__ == "__main__":
    unittest.main()
