"""added the campagin tables

Revision ID: 24052de1fa43
Revises: 
Create Date: 2026-07-03 09:47:56.569397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24052de1fa43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_email', sa.String(), nullable=False),
    sa.Column('account_email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETE', 'FAILED', name='campaign_status'), nullable=False),
    sa.Column('search_filters', sa.JSON(), nullable=True),
    sa.Column('daily_connection_limit', sa.Integer(), nullable=True),
    sa.Column('daily_message_limit', sa.Integer(), nullable=True),
    sa.Column('daily_visit_limit', sa.Integer(), nullable=True),
    sa.Column('connection_note_template', sa.Text(), nullable=True),
    sa.Column('message_templates', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_email'], ['linkedin_accounts.linkedin_email'], ),
    sa.ForeignKeyConstraint(['owner_email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_owner_email'), 'campaigns', ['owner_email'], unique=False)
    op.create_table('campaign_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('VISIT_PROFILE', 'LIKE_POST', 'VISIT_AND_LIKE', 'SEND_CONNECTION', 'SEND_MESSAGE', 'FOLLOW_UP_IF_PENDING', 'THANKS_IF_ACCEPTED', name='campaign_step_type'), nullable=False),
    sa.Column('delay_hours', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_steps_campaign_id'), 'campaign_steps', ['campaign_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('owner_email', sa.String(), nullable=False),
    sa.Column('linkedin_url', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VISITING', 'REQUESTED', 'ACCEPTED', 'MESSAGED', 'REPLIED', 'SKIPPED', 'FAILED', name='lead_status'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('connection_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_campaign_id'), 'leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_leads_owner_email'), 'leads', ['owner_email'], unique=False)
    op.create_table('campaign_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('step_type', sa.String(), nullable=False),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'FAILED', 'SKIPPED', name='job_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_jobs_campaign_id'), 'campaign_jobs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_jobs_lead_id'), 'campaign_jobs', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_jobs_lead_id'), table_name='campaign_jobs')
    op.drop_index(op.f('ix_campaign_jobs_campaign_id'), table_name='campaign_jobs')
    op.drop_table('campaign_jobs')
    op.drop_index(op.f('ix_leads_owner_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_campaign_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_campaign_steps_campaign_id'), table_name='campaign_steps')
    op.drop_table('campaign_steps')
    op.drop_index(op.f('ix_campaigns_owner_email'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
