"""update the lead  tables

Revision ID: 4d1bd4eaa1a3
Revises: 67fd328f7f83
Create Date: 2026-07-03 11:27:11.478840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1bd4eaa1a3'
down_revision: Union[str, Sequence[str], None] = '67fd328f7f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_owner_email'), table_name='leads')
    op.drop_constraint(op.f('leads_owner_email_fkey'), 'leads', type_='foreignkey')
    op.drop_column('leads', 'owner_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('owner_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('leads_owner_email_fkey'), 'leads', 'users', ['owner_email'], ['email'])
    op.create_index(op.f('ix_leads_owner_email'), 'leads', ['owner_email'], unique=False)
    # ### end Alembic commands ###
