"""update the campagin tables

Revision ID: 67fd328f7f83
Revises: 24052de1fa43
Create Date: 2026-07-03 10:20:08.903729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fd328f7f83'
down_revision: Union[str, Sequence[str], None] = '24052de1fa43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_owner_email'), table_name='campaigns')
    op.drop_constraint(op.f('campaigns_owner_email_fkey'), 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'owner_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('owner_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('campaigns_owner_email_fkey'), 'campaigns', 'users', ['owner_email'], ['email'], ondelete='CASCADE')
    op.create_index(op.f('ix_campaigns_owner_email'), 'campaigns', ['owner_email'], unique=False)
    # ### end Alembic commands ###
