"""add valid status to linkedin account

Revision ID: add_valid_status_to_linkedin_account
Revises: change_delay_hours_to_float
Create Date: 2026-07-10

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_valid_status'  # Shortened to fit varchar(32)
down_revision: Union[str, Sequence[str], None] = 'change_delay_hours_to_float'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'valid' to the linkedin_account_status enum
    # PostgreSQL doesn't support IF NOT EXISTS with ALTER TYPE ADD VALUE
    # So we check if the value exists first
    from sqlalchemy import text
    conn = op.get_bind()
    
    # Check if 'valid' already exists in the enum
    result = conn.execute(text("""
        SELECT EXISTS (
            SELECT 1 FROM pg_enum 
            WHERE enumlabel = 'valid' 
            AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'linkedin_account_status')
        )
    """))
    exists = result.scalar()
    
    if not exists:
        conn.execute(text("ALTER TYPE linkedin_account_status ADD VALUE 'valid'"))
        conn.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing enum values is not directly supported in PostgreSQL
    # You would need to create a new enum without the value and migrate data
    # For now, this is a no-op downgrade
    pass
    # ### end Alembic commands ###
