"""add lead complete status and completed_at

Revision ID: add_lead_complete_status
Revises: 67fd328f7f83
Create Date: 2026-07-08

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_lead_complete_status'
down_revision: Union[str, Sequence[str], None] = '67fd328f7f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add COMPLETE status to lead_status enum
    op.execute("ALTER TYPE lead_status ADD VALUE 'complete'")
    
    # Add completed_at column
    op.add_column('leads', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove completed_at column
    op.drop_column('leads', 'completed_at')
    
    # Note: PostgreSQL doesn't support removing enum values directly
    # In production, you would need to create a new enum type without 'complete'
    # and migrate the data, then drop the old type
    # ### end Alembic commands ###
