"""change delay_hours to float for fractional hour support

Revision ID: change_delay_hours_to_float
Revises: add_lead_complete_status
Create Date: 2026-07-10

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'change_delay_hours_to_float'
down_revision: Union[str, Sequence[str], None] = 'add_lead_complete_status'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Change delay_hours from INTEGER to FLOAT to support fractional hours (e.g., 0.083 = 5 minutes)
    op.alter_column('campaign_steps', 'delay_hours',
                    existing_type=sa.Integer(),
                    type_=sa.Float())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert back to INTEGER
    op.alter_column('campaign_steps', 'delay_hours',
                    existing_type=sa.Float(),
                    type_=sa.Integer())
    # ### end Alembic commands ###
