"""revert status column to enum type

Revision ID: revert_status_to_enum
Revises: add_valid_status
Create Date: 2026-07-10

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'revert_status_to_enum'
down_revision: Union[str, Sequence[str], None] = 'add_valid_status'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert status column from String back to Enum type
    op.alter_column('linkedin_accounts', 'status',
                    existing_type=sa.String(),
                    type_=sa.Enum('pending_verification', 'active', 'valid', 'failed', 'suspended', name='linkedin_account_status'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert back to String
    op.alter_column('linkedin_accounts', 'status',
                    existing_type=sa.Enum('pending_verification', 'active', 'valid', 'failed', 'suspended', name='linkedin_account_status'),
                    type_=sa.String())
    # ### end Alembic commands ###
